blank_issues_enabled: false
contact_links:
  - name: â—Issue Template
    url: https://https://github.com/boostcampaitech3/level2-semantic-segmentation-level2-cv-17/issues/new?template=issue_template.md
    about: Please use this default template
